export default {
  plugins: [],
  safelist: [],
  theme: {
    colors: {
      transparent: 'transparent',
      outline: 'var(--color-outline)',
      'outline-active': 'var(--color-outline-active)',
      'surface-pure': 'var(--color-surface-pure)',
      surface: 'var(--color-surface)',
      'surface-secondary': 'var(--color-surface-secondary)',
      'surface-tertiary': 'var(--color-surface-tertiary)',
      'on-surface': 'var(--color-on-surface)',
      'surface-on-secondary': 'var(--color-surface-on-secondary)',
      'surface-on-tertiary': 'var(--color-surface-on-tertiary)',
      'surface-on-inverse': 'var(--color-surface-on-inverse)',
      neutral: 'var(--color-neutral)',
      neutral2: 'var(--color-neutral2)',
      neutral3: 'var(--color-neutral3)',
      'neutral-subtle': 'var(--color-neutral-subtle)',
      'neutral-subtle2': 'var(--color-neutral-subtle2)',
      'neutral-subtle3': 'var(--color-neutral-subtle3)',
      'neutral-bold': 'var(--color-neutral-bold)',
      'on-neutral': 'var(--color-on-neutral)',
      brand: 'var(--color-brand)',
      brand2: 'var(--color-brand2)',
      brand3: 'var(--color-brand3)',
      'brand-subtle': 'var(--color-brand-subtle)',
      'brand-subtle2': 'var(--color-brand-subtle2)',
      'brand-subtle3': 'var(--color-brand-subtle3)',
      'brand-bold': 'var(--color-brand-bold)',
      'on-brand': 'var(--color-on-brand)',
      success: 'var(--color-success)',
      success2: 'var(--color-success2)',
      success3: 'var(--color-success3)',
      'success-subtle': 'var(--color-success-subtle)',
      'success-subtle2': 'var(--color-success-subtle2)',
      'success-subtle3': 'var(--color-success-subtle3)',
      'success-bold': 'var(--color-success-bold)',
      'on-success': 'var(--color-on-success)',
      info: 'var(--color-info)',
      info2: 'var(--color-info2)',
      info3: 'var(--color-info3)',
      'info-subtle': 'var(--color-info-subtle)',
      'info-subtle2': 'var(--color-info-subtle2)',
      'info-subtle3': 'var(--color-info-subtle3)',
      'info-bold': 'var(--color-info-bold)',
      'on-info': 'var(--color-on-info)',
      warning: 'var(--color-warning)',
      warning2: 'var(--color-warning2)',
      warning3: 'var(--color-warning3)',
      'warning-subtle': 'var(--color-warning-subtle)',
      'warning-subtle2': 'var(--color-warning-subtle2)',
      'warning-subtle3': 'var(--color-warning-subtle3)',
      'warning-bold': 'var(--color-warning-bold)',
      'on-warning': 'var(--color-on-warning)',
      danger: 'var(--color-danger)',
      danger2: 'var(--color-danger2)',
      danger3: 'var(--color-danger3)',
      'danger-subtle': 'var(--color-danger-subtle)',
      'danger-subtle2': 'var(--color-danger-subtle2)',
      'danger-subtle3': 'var(--color-danger-subtle3)',
      'danger-bold': 'var(--color-danger-bold)',
      'on-danger': 'var(--color-on-danger)',
      'dialog-background': 'var(--color-dialog-background)',
      'input-background': 'var(--color-input-background)',
      'input-placeholder': 'var(--color-input-placeholder)',
      'overlay-background': 'var(--color-overlay-background)',
    },
    spacing: {
      0: 'var(--spacing-0)',
      '3xs': 'var(--spacing-3xs)',
      '2xs': 'var(--spacing-2xs)',
      xs: 'var(--spacing-xs)',
      sm: 'var(--spacing-sm)',
      base: 'var(--spacing-base)',
      lg: 'var(--spacing-lg)',
      xl: 'var(--spacing-xl)',
      '2xl': 'var(--spacing-2xl)',
    },
    borderRadius: {
      0: 'var(--border-radius-0)',
      xs: 'var(--border-radius-xs)',
      sm: 'var(--border-radius-sm)',
      base: 'var(--border-radius-base)',
      lg: 'var(--border-radius-lg)',
      xl: 'var(--border-radius-xl)',
      full: 'var(--border-radius-full)',
    },
    fontSize: {
      xs: 'var(--font-size-xs)',
      sm: 'var(--font-size-sm)',
      base: 'var(--font-size-base)',
      lg: 'var(--font-size-lg)',
      xl: 'var(--font-size-xl)',
      '2xl': 'var(--font-size-2xl)',
    },
    lineHeight: {
      0: 'var(--line-height-0)',
      sm: 'var(--line-height-sm)',
      base: 'var(--line-height-base)',
      lg: 'var(--line-height-lg)',
      xl: 'var(--line-height-xl)',
      '2xl': 'var(--line-height-2xl)',
    },
    zIndex: {
      overlay: 'var(--z-index-overlay)',
      'combobox-options': 'var(--z-index-combobox-options)',
      'drop-down': 'var(--z-index-drop-down)',
      dialog: 'var(--z-index-dialog)',
      tooltip: 'var(--z-index-tooltip)',
    },
    opacity: {
      0: 'var(--opacity-0)',
      disabled: 'var(--opacity-disabled)',
      full: 'var(--opacity-full)',
    },
    extend: {},
  },
  content: ['./src/**/*.{html,js,svelte,ts}'], // for unused CSS
  variants: { extend: {} },
};
