import { Directive, computed, input } from '@angular/core';
import { angularUtils } from '@organization/shared-utils';
import {
  LucideAlignCenter,
  LucideAlignJustify,
  LucideAlignLeft,
  LucideAlignRight,
  LucideArrowDown,
  LucideArrowLeft,
  LucideArrowRight,
  LucideArrowUp,
  LucideArrowUpRight,
  LucideArrowDownUp,
  LucideAtSign,
  LucideBell,
  LucideBellOff,
  LucideBold,
  LucideBookOpen,
  LucideCalendar,
  LucideChevronDown,
  LucideChevronFirst,
  LucideChevronLast,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronUp,
  LucideChevronsUpDown,
  LucideCheck,
  LucideCircle,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideClock,
  LucideCode,
  LucideCopy,
  LucideEllipsis,
  LucideEllipsisVertical,
  LucideExternalLink,
  LucideDownload,
  LucideFilter,
  LucideGrid2x2,
  LucideImage,
  LucideInbox,
  LucideInfo,
  LucideItalic,
  LucideLink,
  LucideList,
  LucideLoaderCircle,
  LucideLock,
  LucideMail,
  LucideMessageSquare,
  LucideMonitor,
  LucideMoon,
  LucideEye,
  LucideEyeOff,
  LucideOctagonX,
  LucidePalette,
  LucidePaperclip,
  LucideRefreshCw,
  LucideRows3,
  LucideSettings,
  LucideShield,
  LucideStrikethrough,
  LucideSun,
  LucideTriangleAlert,
  LucideUnderline,
  LucideLockKeyhole,
  LucideCircleMinus,
  LucideSquareMinus,
  LucidePencil,
  LucidePlus,
  LucideLogOut,
  LucideLoader,
  LucidePowerOff,
  LucideSquare,
  LucideTrash,
  LucideUpload,
  LucideX,
  LucideCircleX,
  LucideCog,
  LucideSearch,
  LucideSend,
  LucideSparkles,
  type LucideIcon,
  LucideSquareCheckBig,
  LucideCircleCheckBig,
  LucideHouse,
  LucideUsers,
  LucideFileText,
  LucideFolder,
  LucidePackage,
  LucideCreditCard,
  LucideCircleHelp,
  LucideGlobe,
  LucideBriefcase,
  LucideSmartphone,
  LucideLaptop,
  LucideSlidersHorizontal,
  LucidePanelRightClose,
  LucideGripVertical,
} from '@lucide/angular';

/**
 * All registered icon names. This list exists to:
 * - provide type safety via the derived `IconName` type
 * - abstract the icon implementation details away
 * - map semantic names to icons to avoid multiple icons for the same purpose (e.g. `notification` -> `LucideBell`)
 * - catalog which of the 1000+ lucide icons are actually in use
 *
 * When a new icon or semantic name is needed, add to this list.
 */
export const allIconNames = [
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrow-up-right',
  'arrow-down-up',
  'notification',
  'notification-off',
  'calendar',
  'chevron-down',
  'chevron-first',
  'chevron-last',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevron-up-down',
  'check',
  'circle-check-big',
  'cog',
  'square-check-big',
  'circle',
  'copy',
  'ellipsis',
  'download',
  'mail',
  'eye',
  'eye-off',
  'settings',
  'lock-keyhole',
  'circle-minus',
  'square-minus',
  'pencil',
  'plus',
  'log-out',
  'loader',
  'power-off',
  'square',
  'trash',
  'upload',
  'x',
  'circle-x',
  'search',
  'send',
  'sparkles',
  'house',
  'users',
  'file-text',
  'folder',
  'package',
  'credit-card',
  'circle-help',
  'align-center',
  'align-justify',
  'align-left',
  'align-right',
  'at-sign',
  'bold',
  'book-open',
  'circle-alert',
  'circle-check',
  'clock',
  'code',
  'external-link',
  'filter',
  'grid-2x2',
  'image',
  'inbox',
  'info',
  'italic',
  'link',
  'list',
  'loader-circle',
  'lock',
  'message-square',
  'monitor',
  'moon',
  'more',
  'octagon-x',
  'palette',
  'paperclip',
  'refresh-cw',
  'rows-3',
  'shield',
  'strikethrough',
  'sun',
  'triangle-alert',
  'underline',
  'globe',
  'briefcase',
  'smartphone',
  'laptop',
  'sliders-horizontal',
  'panel-right-close',
  'grip-vertical',
] as const;

/** the icon name type derived from all registered icon names */
export type IconName = (typeof allIconNames)[number];

/** default value for the label input */
export const ICON_BRAIN_LABEL_DEFAULT: string | undefined = undefined;

const iconMap: Record<IconName, LucideIcon> = {
  'arrow-down': LucideArrowDown,
  'arrow-left': LucideArrowLeft,
  'arrow-right': LucideArrowRight,
  'arrow-up': LucideArrowUp,
  'arrow-up-right': LucideArrowUpRight,
  'arrow-down-up': LucideArrowDownUp,
  notification: LucideBell,
  'notification-off': LucideBellOff,
  calendar: LucideCalendar,
  'chevron-down': LucideChevronDown,
  'chevron-first': LucideChevronFirst,
  'chevron-last': LucideChevronLast,
  'chevron-left': LucideChevronLeft,
  'chevron-right': LucideChevronRight,
  'chevron-up': LucideChevronUp,
  'chevron-up-down': LucideChevronsUpDown,
  check: LucideCheck,
  'circle-check-big': LucideCircleCheckBig,
  cog: LucideCog,
  'square-check-big': LucideSquareCheckBig,
  circle: LucideCircle,
  copy: LucideCopy,
  ellipsis: LucideEllipsis,
  download: LucideDownload,
  mail: LucideMail,
  eye: LucideEye,
  'eye-off': LucideEyeOff,
  settings: LucideSettings,
  'lock-keyhole': LucideLockKeyhole,
  'circle-minus': LucideCircleMinus,
  'square-minus': LucideSquareMinus,
  pencil: LucidePencil,
  plus: LucidePlus,
  'log-out': LucideLogOut,
  loader: LucideLoader,
  'power-off': LucidePowerOff,
  square: LucideSquare,
  trash: LucideTrash,
  upload: LucideUpload,
  x: LucideX,
  'circle-x': LucideCircleX,
  search: LucideSearch,
  send: LucideSend,
  sparkles: LucideSparkles,
  house: LucideHouse,
  users: LucideUsers,
  'file-text': LucideFileText,
  folder: LucideFolder,
  package: LucidePackage,
  'credit-card': LucideCreditCard,
  'circle-help': LucideCircleHelp,
  'align-center': LucideAlignCenter,
  'align-justify': LucideAlignJustify,
  'align-left': LucideAlignLeft,
  'align-right': LucideAlignRight,
  'at-sign': LucideAtSign,
  bold: LucideBold,
  'book-open': LucideBookOpen,
  'circle-alert': LucideCircleAlert,
  'circle-check': LucideCircleCheck,
  clock: LucideClock,
  code: LucideCode,
  'external-link': LucideExternalLink,
  filter: LucideFilter,
  'grid-2x2': LucideGrid2x2,
  image: LucideImage,
  inbox: LucideInbox,
  info: LucideInfo,
  italic: LucideItalic,
  link: LucideLink,
  list: LucideList,
  'loader-circle': LucideLoaderCircle,
  lock: LucideLock,
  'message-square': LucideMessageSquare,
  monitor: LucideMonitor,
  moon: LucideMoon,
  more: LucideEllipsisVertical,
  'octagon-x': LucideOctagonX,
  palette: LucidePalette,
  paperclip: LucidePaperclip,
  'refresh-cw': LucideRefreshCw,
  'rows-3': LucideRows3,
  shield: LucideShield,
  strikethrough: LucideStrikethrough,
  sun: LucideSun,
  'triangle-alert': LucideTriangleAlert,
  underline: LucideUnderline,
  globe: LucideGlobe,
  briefcase: LucideBriefcase,
  smartphone: LucideSmartphone,
  laptop: LucideLaptop,
  'sliders-horizontal': LucideSlidersHorizontal,
  'panel-right-close': LucidePanelRightClose,
  'grip-vertical': LucideGripVertical,
};

/**
 * headless brain directive for the icon. owns the semantic icon name registry, the lucide icon resolution logic,
 * and the accessibility derivation (role, aria-label, aria-hidden) for the rendered svg. carries no styling,
 * sizing, or color concerns — apply it to a presentation component via hostDirectives.
 */
@Directive({
  selector: '[orgIconBrain]',
  exportAs: 'orgIconBrain',
})
export class IconBrainDirective {
  /** the semantic name of the icon to render */
  public readonly name = input.required<IconName>();

  /**
   * accessible label for the icon; when provided the icon is treated as meaningful (role="img") and aria-hidden
   * is removed; omit for decorative icons
   */
  public readonly label = input<string | undefined, string | null | undefined>(ICON_BRAIN_LABEL_DEFAULT, {
    transform: angularUtils.transformNullToUndefined,
  });

  /** the resolved lucide icon object derived from the name input */
  public readonly lucideIcon = computed<LucideIcon>(() => iconMap[this.name()]);

  /** aria-hidden attribute value — true for decorative icons (no label), null when the icon is meaningful */
  public readonly ariaHidden = computed<true | null>(() => (this.label() ? null : true));

  /** aria-label attribute value — the label string when meaningful, null when decorative */
  public readonly ariaLabel = computed<string | null>(() => this.label() ?? null);

  /** role attribute value — "img" when the icon has a label, null when decorative */
  public readonly role = computed<'img' | null>(() => (this.label() ? 'img' : null));
}
